apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: myspringapp
spec:
  replicas: 1
  selector:
    app: myspringapp
  template:
    metadata:
      labels:
        app: myspringapp
    spec:
      containers:
        - name: myspringapp
          image: 'myspringapp:latest'
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 3

          env:
            - name: JAVA_OPTS
              value: '-Xmx512m'
